language: node_js

services:
  - docker

node_js:
  - "node"
  
install:
  - npm install
  - npm install --no-save nyc coveralls

script:
  - npm run test-ci

after_script:
  - nyc report --reporter=text-lcov | coveralls