version: '2'
services:
  db:
    image: postgres
    env_file:
      - ../env/test/db.env
#    ports:
#      - "5432:5432"
    networks:
      nucleotid_net:
        ipv4_address: 192.168.100.13
    volumes:
      - ../db/test/data:/var/lib/postgresql/data

  node:
    image: node:8
    working_dir: /app
    command: bash -c "export NODE_ENV=test && node db/test_db.js && ./node_modules/.bin/nyc npm run test"
    env_file:
      - ../env/test/db.env
      - ../env/test/node.env
#    ports:
#      - "3000:3000"
#      - "80:80"
#      - "443:443"
    depends_on:
      - db
    networks:
      nucleotid_net:
        ipv4_address: 192.168.100.12
    volumes:
      - ../:/app

networks:
  nucleotid_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 192.168.100.0/24
        gateway: 192.168.100.1